'use client'

import Link from 'next/link'
import { ArrowRight, Minus, Plus, Trash2 } from 'lucide-react'
import { PortalHeader } from '@/components/portal-header'
import { useCart } from '@/components/providers'
import { formatPounds } from '@/lib/format'
import { Button } from '@/components/ui/button'

export default function CartPage() {
  const { items, updateQuantity, removeItem, subtotal, ready } = useCart()
  if (!ready) return <div className="min-h-screen bg-background"><PortalHeader /><div className="mx-auto max-w-3xl px-5 py-20 text-center text-muted-foreground">Loading basket…</div></div>
  return <div className="min-h-screen bg-background"><PortalHeader /><main className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><p className="text-sm font-bold uppercase tracking-[.14em] text-primary">Your order</p><h1 className="mt-2 font-serif text-4xl font-extrabold tracking-tight">Basket</h1>{!items.length ? <div className="mt-10 rounded-3xl border border-dashed p-16 text-center"><h2 className="font-serif text-2xl font-bold">Your basket is empty</h2><p className="mt-2 text-sm text-muted-foreground">Browse the catalogue to add your first wholesale item.</p><Button asChild className="mt-6"><Link href="/catalogue">Browse catalogue <ArrowRight /></Link></Button></div> : <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{items.map(({ product, quantity }) => <div key={product.id} className="flex gap-4 rounded-2xl border border-border bg-card p-4"><div className="min-w-0 flex-1"><Link href={`/products/${product.id}`} className="font-serif text-lg font-bold hover:text-primary">{product.name}</Link><p className="mt-1 text-sm text-muted-foreground">{product.pack ?? 'Wholesale pack'} · {formatPounds(product.price)} per pack</p><div className="mt-4 flex items-center gap-3"><div className="flex items-center rounded-lg border border-input"><button type="button" onClick={() => updateQuantity(product.id, quantity - 1)} className="p-2 hover:bg-muted" aria-label="Decrease quantity"><Minus className="size-4" /></button><span className="min-w-8 text-center text-sm font-bold">{quantity}</span><button type="button" onClick={() => updateQuantity(product.id, quantity + 1)} className="p-2 hover:bg-muted" aria-label="Increase quantity"><Plus className="size-4" /></button></div><button type="button" onClick={() => removeItem(product.id)} className="inline-flex items-center gap-1 text-xs font-bold text-muted-foreground hover:text-destructive"><Trash2 className="size-3.5" /> Remove</button></div></div><p className="font-serif text-lg font-extrabold">{formatPounds((product.price ?? 0) * quantity)}</p></div>)}</div><aside className="h-fit rounded-2xl border border-border bg-card p-5"><h2 className="font-serif text-xl font-bold">Order summary</h2><div className="mt-5 flex justify-between text-sm"><span className="text-muted-foreground">Subtotal</span><span className="font-bold">{formatPounds(subtotal)}</span></div><p className="mt-3 text-xs leading-5 text-muted-foreground">Delivery is arranged after we review your address and order.</p><div className="my-5 border-t border-border" /><div className="flex justify-between"><span className="font-bold">Estimated total</span><span className="font-serif text-xl font-extrabold">{formatPounds(subtotal)}</span></div><Button asChild className="mt-6 w-full" size="lg"><Link href="/checkout">Continue to delivery <ArrowRight /></Link></Button></aside></div>}</main></div>
}
